repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.63.11
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your codebase.
        entry: trufflehog git file://. --only-verified --fail
        language: system
        stages: [commit, push]

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.256
    hooks:
      - id: checkov
        args: [--quiet, --compact, --soft-fail]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["-S", "error"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yml"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint
